######################################################################
# Automatically generated by qmake (3.0) Tue Apr 9 11:36:23 2019
######################################################################
system(./makeversion.sh) QMAKE_EXTRA_TARGETS += version
PRE_TARGETDEPS += version.h
QT += core gui
TEMPLATE = app
DESTDIR = bin
TARGET = touchinjector
CONFIG   += c++11
INCLUDEPATH += .

# Input
SOURCES += main.cpp \ 
			ui.cpp
# FB stuff
LIBS += -lqsgepaper

